import { MigrationInterface, QueryRunner } from "typeorm";

export class InitialSchema1773930803582 implements MigrationInterface {
    name = 'InitialSchema1773930803582'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "permissions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "permission_code" character varying(100) NOT NULL, "permission_name" character varying(100) NOT NULL, "description" character varying(255), "permission_type" character varying(20) NOT NULL, "module" character varying(50) NOT NULL, "sort_order" integer NOT NULL DEFAULT '0', "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "UQ_f65dbbe5dc253ff51e8a1f894df" UNIQUE ("permission_code"), CONSTRAINT "PK_920331560282b8bd21bb02290df" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_c87bc220c276c0281bc0610885" ON "permissions" ("permission_type") `);
        await queryRunner.query(`CREATE INDEX "IDX_8b634526cdd01f2adba6c7ac07" ON "permissions" ("module") `);
        await queryRunner.query(`CREATE TABLE "roles" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "role_name" character varying(50) NOT NULL, "role_code" character varying(50) NOT NULL, "description" character varying(255), "is_system" boolean NOT NULL DEFAULT false, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "UQ_3feee96f9a604421f24496988db" UNIQUE ("role_code"), CONSTRAINT "PK_c1433d71a4838793a49dcad46ab" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "users" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, "username" character varying(50) NOT NULL, "password_hash" character varying(255) NOT NULL, "display_name" character varying(100) NOT NULL, "email" character varying(120), "phone" character varying(50), "status" character varying(20) NOT NULL DEFAULT 'ACTIVE', "failed_login_count" integer NOT NULL DEFAULT '0', "locked_until" TIMESTAMP WITH TIME ZONE, CONSTRAINT "UQ_fe0bb3f6520ee0469504521e710" UNIQUE ("username"), CONSTRAINT "PK_a3ffb1c0c8416b9fc6f907b7433" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_3676155292d72c67cd4e090514" ON "users" ("status") `);
        await queryRunner.query(`CREATE TABLE "company_info" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "customer_id" uuid NOT NULL, "corporation_number" character varying(50), "fiscal_month" smallint, "representative_name" character varying(120), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "UQ_6988c6cbd6fb66f2fcbb27f0867" UNIQUE ("customer_id"), CONSTRAINT "REL_6988c6cbd6fb66f2fcbb27f086" UNIQUE ("customer_id"), CONSTRAINT "PK_88c3e323679d0747ffbb83f3f78" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "person_info" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "customer_id" uuid NOT NULL, "nationality" character varying(80), "residence_status" character varying(100), "residence_expire_date" date, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "UQ_e864b9151380458dd0af28f6e44" UNIQUE ("customer_id"), CONSTRAINT "REL_e864b9151380458dd0af28f6e4" UNIQUE ("customer_id"), CONSTRAINT "PK_8e337871eee4312823dca962cc1" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "notes" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, "customer_id" uuid NOT NULL, "content" text NOT NULL, "note_type" character varying(30) NOT NULL DEFAULT 'GENERAL', "created_by" uuid, CONSTRAINT "PK_af6206538ea96c4e77e9f400c3d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_e04c36c14bc9f01f84cd7655b6" ON "notes" ("customer_id") `);
        await queryRunner.query(`CREATE TABLE "customer_staff_relations" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "customer_id" uuid NOT NULL, "user_id" uuid NOT NULL, "relation_type" character varying(30) NOT NULL DEFAULT 'PRIMARY', "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_3db78461fef7bb5641a8e7fa63b" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_c8b5f30220b46fcf4c64b4f6cc" ON "customer_staff_relations" ("customer_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_98f3bd72761ece595aa544cd8a" ON "customer_staff_relations" ("user_id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_29f12cee9b015a4fb82fd016d0" ON "customer_staff_relations" ("customer_id", "user_id") `);
        await queryRunner.query(`CREATE TABLE "customers" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, "customer_code" character varying(50) NOT NULL, "customer_type" character varying(20) NOT NULL, "customer_name" character varying(200) NOT NULL, "phone" character varying(50), "email" character varying(120), "address" character varying(500), "service_type" character varying(20) NOT NULL, "owner_user_id" uuid, "status" character varying(20) NOT NULL DEFAULT 'ACTIVE', "created_by" uuid, "updated_by" uuid, CONSTRAINT "UQ_acd5656a9fa7cf04125f0848165" UNIQUE ("customer_code"), CONSTRAINT "PK_133ec679a801fab5e070f73d3ea" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_a1dded0c9e77a3e62a09d20ed8" ON "customers" ("customer_name") `);
        await queryRunner.query(`CREATE INDEX "IDX_724f8799ff8921a88eb5253d2f" ON "customers" ("service_type") `);
        await queryRunner.query(`CREATE INDEX "IDX_94c3faf411893c9065d8e3a1ba" ON "customers" ("owner_user_id") `);
        await queryRunner.query(`CREATE TABLE "tax_contracts" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, "customer_id" uuid NOT NULL, "contract_name" character varying(200) NOT NULL, "contract_status" character varying(30) NOT NULL DEFAULT 'ACTIVE', "billing_cycle" character varying(20) NOT NULL DEFAULT 'MONTHLY', "start_date" date NOT NULL, "end_date" date, "monthly_fee" numeric(18,2) NOT NULL DEFAULT '0', "owner_user_id" uuid, "created_by" uuid, "updated_by" uuid, CONSTRAINT "PK_0f5a77c23898c83967903b9a261" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_a8432b1e19fcd81c5109c4759e" ON "tax_contracts" ("customer_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_3d138da760f80cf89b6a1bbeaf" ON "tax_contracts" ("contract_status") `);
        await queryRunner.query(`CREATE INDEX "IDX_1bf8524bb25eab63d2e91af0d2" ON "tax_contracts" ("owner_user_id") `);
        await queryRunner.query(`CREATE TABLE "files" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, "customer_id" uuid, "business_type" character varying(30) NOT NULL, "related_id" uuid, "file_name" character varying(255) NOT NULL, "description" character varying(500), "file_path" character varying(1000) NOT NULL, "file_ext" character varying(20), "file_size" bigint, "mime_type" character varying(100), "uploaded_by" uuid, CONSTRAINT "PK_6c16b9093a142e0e7613b04a3d9" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_56c45a88d18bd08a3abaa532a2" ON "files" ("customer_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_e9f32fe4b7bcf2dfb8751d0a87" ON "files" ("business_type") `);
        await queryRunner.query(`CREATE INDEX "IDX_d2eddbeffbb889f6dbc4000259" ON "files" ("related_id") `);
        await queryRunner.query(`CREATE TABLE "tax_monthly_documents" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "tax_period_id" uuid NOT NULL, "file_id" uuid, "document_name" character varying(200) NOT NULL, "received" boolean NOT NULL DEFAULT false, "received_at" TIMESTAMP WITH TIME ZONE, "remark" character varying(500), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_ffb5a9927ba0ec7467197563221" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_a53a90090faa683e0766caeda7" ON "tax_monthly_documents" ("tax_period_id") `);
        await queryRunner.query(`CREATE TABLE "tax_monthly_work_items" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "tax_period_id" uuid NOT NULL, "item_name" character varying(200) NOT NULL, "completed" boolean NOT NULL DEFAULT false, "completed_at" TIMESTAMP WITH TIME ZONE, "completed_by" uuid, "remark" character varying(500), "sort_order" integer NOT NULL DEFAULT '0', "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_4500d6607f44ba98b0b5c8554d9" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_63b37f04b3cf07386071d1dac8" ON "tax_monthly_work_items" ("tax_period_id") `);
        await queryRunner.query(`CREATE TABLE "tax_periods" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, "tax_contract_id" uuid NOT NULL, "customer_id" uuid NOT NULL, "period_ym" character varying(7) NOT NULL, "declaration_deadline" date, "monthly_status" character varying(30) NOT NULL DEFAULT 'NOT_STARTED', "material_status" character varying(30) NOT NULL DEFAULT 'NOT_RECEIVED', "created_by" uuid, CONSTRAINT "PK_545a9e88972074bf0d06f37b039" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_78aef69f2e1dfa2a078553bfb6" ON "tax_periods" ("tax_contract_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_d81a96128c1c18a27887579b9b" ON "tax_periods" ("customer_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_8d48b76ad9c949f2da6bd72369" ON "tax_periods" ("monthly_status") `);
        await queryRunner.query(`CREATE TABLE "login_logs" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "user_id" uuid, "username" character varying(50) NOT NULL, "login_type" character varying(20) NOT NULL, "ip_address" character varying(50), "device_info" character varying(255), "result" character varying(20) NOT NULL, "failure_reason" character varying(255), "occurred_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(), CONSTRAINT "PK_15f7b02ad55d5ba905b2962ebab" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_e2dffa109d0d3dbd94a0a51669" ON "login_logs" ("user_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_2b01a6f73584d7fde0ed64435c" ON "login_logs" ("occurred_at") `);
        await queryRunner.query(`CREATE TABLE "export_logs" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "user_id" uuid NOT NULL, "export_type" character varying(50) NOT NULL, "export_params" jsonb, "file_name" character varying(255), "status" character varying(20) NOT NULL, "occurred_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(), CONSTRAINT "PK_cba8d8105ac48685076eb2c81e3" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_65c069f353e9ea9fe3f6704ca6" ON "export_logs" ("user_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_7a21cf8208b231827f76a53f6b" ON "export_logs" ("occurred_at") `);
        await queryRunner.query(`CREATE TABLE "audit_logs" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "user_id" uuid, "action_type" character varying(50) NOT NULL, "target_type" character varying(50), "target_id" uuid, "before_value" jsonb, "after_value" jsonb, "ip_address" character varying(50), "device_info" character varying(255), "result" character varying(20), "occurred_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(), CONSTRAINT "PK_1bb179d048bbc581caa3b013439" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_bd2726fd31b35443f2245b93ba" ON "audit_logs" ("user_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_0a18c37e4353a67e70f7924e86" ON "audit_logs" ("action_type") `);
        await queryRunner.query(`CREATE INDEX "IDX_f40ca89b34f101a09acc17c62a" ON "audit_logs" ("target_type") `);
        await queryRunner.query(`CREATE INDEX "IDX_36cd4615fabad14abad075ffc9" ON "audit_logs" ("occurred_at") `);
        await queryRunner.query(`CREATE TABLE "invoice_items" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "invoice_id" uuid NOT NULL, "description" character varying(500) NOT NULL, "quantity" integer NOT NULL DEFAULT '1', "unit_price" numeric(18,2) NOT NULL DEFAULT '0', "amount" numeric(18,2) NOT NULL DEFAULT '0', "sort_order" integer NOT NULL DEFAULT '0', "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_53b99f9e0e2945e69de1a12b75a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_dc991d555664682cfe892eea2c" ON "invoice_items" ("invoice_id") `);
        await queryRunner.query(`CREATE TABLE "invoices" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, "customer_id" uuid NOT NULL, "invoice_no" character varying(50) NOT NULL, "invoice_type" character varying(30) NOT NULL, "total_amount" numeric(18,2) NOT NULL DEFAULT '0', "currency" character varying(10) NOT NULL DEFAULT 'JPY', "status" character varying(30) NOT NULL DEFAULT 'DRAFT', "due_date" date, "issued_at" date, "related_id" uuid, "related_type" character varying(30), "remark" text, "created_by" uuid, "updated_by" uuid, "void_reason" character varying(500), "voided_at" TIMESTAMP WITH TIME ZONE, "voided_by" uuid, CONSTRAINT "PK_668cef7c22a427fd822cc1be3ce" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_65e3145f317bd655481d3f96c7" ON "invoices" ("customer_id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_37669c562a2525929927d9d691" ON "invoices" ("invoice_no") `);
        await queryRunner.query(`CREATE INDEX "IDX_ac0f09364e3701d9ed35435288" ON "invoices" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_0457ee681a50419881ea2ee796" ON "invoices" ("due_date") `);
        await queryRunner.query(`CREATE TABLE "payment_allocations" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "payment_id" uuid NOT NULL, "invoice_id" uuid NOT NULL, "allocated_amount" numeric(18,2) NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "created_by" uuid, CONSTRAINT "PK_a5c6ff22065ac772620c85f4efb" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_4348f49c6822420b9503ba880b" ON "payment_allocations" ("payment_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_72095d7b95a6168756ea7d4fbc" ON "payment_allocations" ("invoice_id") `);
        await queryRunner.query(`CREATE TABLE "payments" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, "customer_id" uuid NOT NULL, "payment_no" character varying(50) NOT NULL, "payment_date" date NOT NULL, "payment_amount" numeric(18,2) NOT NULL, "payment_method" character varying(30) NOT NULL, "status" character varying(30) NOT NULL DEFAULT 'REGISTERED', "remark" character varying(500), "created_by" uuid, "reversed_at" TIMESTAMP WITH TIME ZONE, "reversed_by" uuid, "reversal_reason" character varying(500), CONSTRAINT "PK_197ab7af18c93fbb0c9b28b4a59" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_d0b02233df1c52323107fe7b4d" ON "payments" ("customer_id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_8aaa54db3d9827cba0999b7fb2" ON "payments" ("payment_no") `);
        await queryRunner.query(`CREATE INDEX "IDX_32b41cdb985a296213e9a928b5" ON "payments" ("status") `);
        await queryRunner.query(`CREATE TABLE "deposit_accounts" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "customer_id" uuid NOT NULL, "balance" numeric(18,2) NOT NULL DEFAULT '0', "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "REL_433a90689f5b2d8145c5afcb10" UNIQUE ("customer_id"), CONSTRAINT "PK_3251b32cdecdba88387145ebba0" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_433a90689f5b2d8145c5afcb10" ON "deposit_accounts" ("customer_id") `);
        await queryRunner.query(`CREATE TABLE "deposit_transactions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "deposit_account_id" uuid NOT NULL, "transaction_type" character varying(30) NOT NULL, "amount" numeric(18,2) NOT NULL, "balance_after" numeric(18,2) NOT NULL, "related_invoice_id" uuid, "remark" character varying(500), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "created_by" uuid, CONSTRAINT "PK_40b622c6ce8f9887736b0fdb420" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_492c9485c10fa86f5021114528" ON "deposit_transactions" ("deposit_account_id") `);
        await queryRunner.query(`CREATE TABLE "file_access_logs" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "file_id" uuid NOT NULL, "user_id" uuid, "action" character varying(20) NOT NULL, "ip_address" character varying(50), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_be1d3092396a30ffa25b0e9c7e8" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_f1101a0737439a005eb075a8f2" ON "file_access_logs" ("file_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_fe32f075b4210b25158b5be1e3" ON "file_access_logs" ("user_id") `);
        await queryRunner.query(`CREATE TABLE "admin_case_interviews" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, "admin_case_id" uuid NOT NULL, "customer_id" uuid NOT NULL, "interview_date" date NOT NULL, "interview_location" character varying(200), "content" text NOT NULL, "created_by" uuid, CONSTRAINT "PK_45071b3bca1085e4f81d9602f87" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_60a2d43baaac01885149971b62" ON "admin_case_interviews" ("admin_case_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_e59cb029ad14d4e405bf18c404" ON "admin_case_interviews" ("customer_id") `);
        await queryRunner.query(`CREATE TABLE "admin_case_documents" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "admin_case_id" uuid NOT NULL, "file_id" uuid NOT NULL, "document_type" character varying(50), "remark" character varying(500), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_52b8bd9563667a00a7210513451" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_1b25bf0cafc578e0324cff5004" ON "admin_case_documents" ("admin_case_id") `);
        await queryRunner.query(`CREATE TABLE "admin_case_tasks" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, "admin_case_id" uuid NOT NULL, "task_name" character varying(200) NOT NULL, "status" character varying(30) NOT NULL DEFAULT 'TODO', "assignee_id" uuid, "due_date" date, "description" text, "completed_at" TIMESTAMP WITH TIME ZONE, "created_by" uuid, CONSTRAINT "PK_fe63502ea2dedfbe8c07d515648" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_a195e34a6d72fc2fc661c2f1ae" ON "admin_case_tasks" ("admin_case_id") `);
        await queryRunner.query(`CREATE TABLE "admin_cases" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, "customer_id" uuid NOT NULL, "case_name" character varying(200) NOT NULL, "applicant_name" character varying(120), "residence_status" character varying(100), "status" character varying(30) NOT NULL DEFAULT 'DRAFT', "expire_date" date, "owner_user_id" uuid, "created_by" uuid, "updated_by" uuid, CONSTRAINT "PK_4c71e638426fbf3c6f9352391b8" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_515fd84b2a57abbc158687363e" ON "admin_cases" ("customer_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_0b8e796a94e331a83318cf41b3" ON "admin_cases" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_894c17b2b011c55246fe50f078" ON "admin_cases" ("expire_date") `);
        await queryRunner.query(`CREATE INDEX "IDX_9d42389a1dd5856406b9a8c728" ON "admin_cases" ("owner_user_id") `);
        await queryRunner.query(`CREATE TABLE "role_permissions" ("role_id" uuid NOT NULL, "permission_id" uuid NOT NULL, CONSTRAINT "PK_25d24010f53bb80b78e412c9656" PRIMARY KEY ("role_id", "permission_id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_178199805b901ccd220ab7740e" ON "role_permissions" ("role_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_17022daf3f885f7d35423e9971" ON "role_permissions" ("permission_id") `);
        await queryRunner.query(`CREATE TABLE "user_roles" ("user_id" uuid NOT NULL, "role_id" uuid NOT NULL, CONSTRAINT "PK_23ed6f04fe43066df08379fd034" PRIMARY KEY ("user_id", "role_id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_87b8888186ca9769c960e92687" ON "user_roles" ("user_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_b23c65e50a758245a33ee35fda" ON "user_roles" ("role_id") `);
        await queryRunner.query(`ALTER TABLE "company_info" ADD CONSTRAINT "FK_6988c6cbd6fb66f2fcbb27f0867" FOREIGN KEY ("customer_id") REFERENCES "customers"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "person_info" ADD CONSTRAINT "FK_e864b9151380458dd0af28f6e44" FOREIGN KEY ("customer_id") REFERENCES "customers"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "notes" ADD CONSTRAINT "FK_e04c36c14bc9f01f84cd7655b68" FOREIGN KEY ("customer_id") REFERENCES "customers"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "notes" ADD CONSTRAINT "FK_b86c5f2b5de1e7a3d2a428cfb55" FOREIGN KEY ("created_by") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "customer_staff_relations" ADD CONSTRAINT "FK_c8b5f30220b46fcf4c64b4f6cc0" FOREIGN KEY ("customer_id") REFERENCES "customers"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "customer_staff_relations" ADD CONSTRAINT "FK_98f3bd72761ece595aa544cd8ab" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "customers" ADD CONSTRAINT "FK_94c3faf411893c9065d8e3a1ba5" FOREIGN KEY ("owner_user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tax_contracts" ADD CONSTRAINT "FK_a8432b1e19fcd81c5109c4759e3" FOREIGN KEY ("customer_id") REFERENCES "customers"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tax_contracts" ADD CONSTRAINT "FK_1bf8524bb25eab63d2e91af0d2d" FOREIGN KEY ("owner_user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "files" ADD CONSTRAINT "FK_63c92c51cd7fd95c2d79d709b61" FOREIGN KEY ("uploaded_by") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tax_monthly_documents" ADD CONSTRAINT "FK_a53a90090faa683e0766caeda71" FOREIGN KEY ("tax_period_id") REFERENCES "tax_periods"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tax_monthly_documents" ADD CONSTRAINT "FK_70aec29b537b44c1d25e352821e" FOREIGN KEY ("file_id") REFERENCES "files"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tax_monthly_work_items" ADD CONSTRAINT "FK_63b37f04b3cf07386071d1dac83" FOREIGN KEY ("tax_period_id") REFERENCES "tax_periods"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tax_monthly_work_items" ADD CONSTRAINT "FK_eacc9c2849a6d64ab1852a7efd9" FOREIGN KEY ("completed_by") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tax_periods" ADD CONSTRAINT "FK_78aef69f2e1dfa2a078553bfb67" FOREIGN KEY ("tax_contract_id") REFERENCES "tax_contracts"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tax_periods" ADD CONSTRAINT "FK_d81a96128c1c18a27887579b9bf" FOREIGN KEY ("customer_id") REFERENCES "customers"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "login_logs" ADD CONSTRAINT "FK_e2dffa109d0d3dbd94a0a51669c" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "export_logs" ADD CONSTRAINT "FK_65c069f353e9ea9fe3f6704ca6f" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "audit_logs" ADD CONSTRAINT "FK_bd2726fd31b35443f2245b93ba0" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "invoice_items" ADD CONSTRAINT "FK_dc991d555664682cfe892eea2c1" FOREIGN KEY ("invoice_id") REFERENCES "invoices"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "invoices" ADD CONSTRAINT "FK_65e3145f317bd655481d3f96c74" FOREIGN KEY ("customer_id") REFERENCES "customers"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "payment_allocations" ADD CONSTRAINT "FK_4348f49c6822420b9503ba880b8" FOREIGN KEY ("payment_id") REFERENCES "payments"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "payment_allocations" ADD CONSTRAINT "FK_72095d7b95a6168756ea7d4fbc5" FOREIGN KEY ("invoice_id") REFERENCES "invoices"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "payments" ADD CONSTRAINT "FK_d0b02233df1c52323107fe7b4d7" FOREIGN KEY ("customer_id") REFERENCES "customers"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "deposit_accounts" ADD CONSTRAINT "FK_433a90689f5b2d8145c5afcb109" FOREIGN KEY ("customer_id") REFERENCES "customers"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "deposit_transactions" ADD CONSTRAINT "FK_492c9485c10fa86f5021114528f" FOREIGN KEY ("deposit_account_id") REFERENCES "deposit_accounts"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "deposit_transactions" ADD CONSTRAINT "FK_7ba5c7ff459f4c33a6988c431a0" FOREIGN KEY ("related_invoice_id") REFERENCES "invoices"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "file_access_logs" ADD CONSTRAINT "FK_f1101a0737439a005eb075a8f2d" FOREIGN KEY ("file_id") REFERENCES "files"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "file_access_logs" ADD CONSTRAINT "FK_fe32f075b4210b25158b5be1e3e" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "admin_case_interviews" ADD CONSTRAINT "FK_60a2d43baaac01885149971b627" FOREIGN KEY ("admin_case_id") REFERENCES "admin_cases"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "admin_case_interviews" ADD CONSTRAINT "FK_e59cb029ad14d4e405bf18c404a" FOREIGN KEY ("customer_id") REFERENCES "customers"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "admin_case_interviews" ADD CONSTRAINT "FK_43d3bf5fa352ddbc34ac9d87452" FOREIGN KEY ("created_by") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "admin_case_documents" ADD CONSTRAINT "FK_1b25bf0cafc578e0324cff50049" FOREIGN KEY ("admin_case_id") REFERENCES "admin_cases"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "admin_case_documents" ADD CONSTRAINT "FK_a4498c3d4a1051589ae7d1496ad" FOREIGN KEY ("file_id") REFERENCES "files"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "admin_case_tasks" ADD CONSTRAINT "FK_a195e34a6d72fc2fc661c2f1ae0" FOREIGN KEY ("admin_case_id") REFERENCES "admin_cases"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "admin_case_tasks" ADD CONSTRAINT "FK_d499cd66439dfb9254a02c03db4" FOREIGN KEY ("assignee_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "admin_case_tasks" ADD CONSTRAINT "FK_2246b9741216a739ff89470a84e" FOREIGN KEY ("created_by") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "admin_cases" ADD CONSTRAINT "FK_515fd84b2a57abbc158687363e3" FOREIGN KEY ("customer_id") REFERENCES "customers"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "admin_cases" ADD CONSTRAINT "FK_9d42389a1dd5856406b9a8c7284" FOREIGN KEY ("owner_user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "role_permissions" ADD CONSTRAINT "FK_178199805b901ccd220ab7740ec" FOREIGN KEY ("role_id") REFERENCES "roles"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "role_permissions" ADD CONSTRAINT "FK_17022daf3f885f7d35423e9971e" FOREIGN KEY ("permission_id") REFERENCES "permissions"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_roles" ADD CONSTRAINT "FK_87b8888186ca9769c960e926870" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "user_roles" ADD CONSTRAINT "FK_b23c65e50a758245a33ee35fda1" FOREIGN KEY ("role_id") REFERENCES "roles"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "user_roles" DROP CONSTRAINT "FK_b23c65e50a758245a33ee35fda1"`);
        await queryRunner.query(`ALTER TABLE "user_roles" DROP CONSTRAINT "FK_87b8888186ca9769c960e926870"`);
        await queryRunner.query(`ALTER TABLE "role_permissions" DROP CONSTRAINT "FK_17022daf3f885f7d35423e9971e"`);
        await queryRunner.query(`ALTER TABLE "role_permissions" DROP CONSTRAINT "FK_178199805b901ccd220ab7740ec"`);
        await queryRunner.query(`ALTER TABLE "admin_cases" DROP CONSTRAINT "FK_9d42389a1dd5856406b9a8c7284"`);
        await queryRunner.query(`ALTER TABLE "admin_cases" DROP CONSTRAINT "FK_515fd84b2a57abbc158687363e3"`);
        await queryRunner.query(`ALTER TABLE "admin_case_tasks" DROP CONSTRAINT "FK_2246b9741216a739ff89470a84e"`);
        await queryRunner.query(`ALTER TABLE "admin_case_tasks" DROP CONSTRAINT "FK_d499cd66439dfb9254a02c03db4"`);
        await queryRunner.query(`ALTER TABLE "admin_case_tasks" DROP CONSTRAINT "FK_a195e34a6d72fc2fc661c2f1ae0"`);
        await queryRunner.query(`ALTER TABLE "admin_case_documents" DROP CONSTRAINT "FK_a4498c3d4a1051589ae7d1496ad"`);
        await queryRunner.query(`ALTER TABLE "admin_case_documents" DROP CONSTRAINT "FK_1b25bf0cafc578e0324cff50049"`);
        await queryRunner.query(`ALTER TABLE "admin_case_interviews" DROP CONSTRAINT "FK_43d3bf5fa352ddbc34ac9d87452"`);
        await queryRunner.query(`ALTER TABLE "admin_case_interviews" DROP CONSTRAINT "FK_e59cb029ad14d4e405bf18c404a"`);
        await queryRunner.query(`ALTER TABLE "admin_case_interviews" DROP CONSTRAINT "FK_60a2d43baaac01885149971b627"`);
        await queryRunner.query(`ALTER TABLE "file_access_logs" DROP CONSTRAINT "FK_fe32f075b4210b25158b5be1e3e"`);
        await queryRunner.query(`ALTER TABLE "file_access_logs" DROP CONSTRAINT "FK_f1101a0737439a005eb075a8f2d"`);
        await queryRunner.query(`ALTER TABLE "deposit_transactions" DROP CONSTRAINT "FK_7ba5c7ff459f4c33a6988c431a0"`);
        await queryRunner.query(`ALTER TABLE "deposit_transactions" DROP CONSTRAINT "FK_492c9485c10fa86f5021114528f"`);
        await queryRunner.query(`ALTER TABLE "deposit_accounts" DROP CONSTRAINT "FK_433a90689f5b2d8145c5afcb109"`);
        await queryRunner.query(`ALTER TABLE "payments" DROP CONSTRAINT "FK_d0b02233df1c52323107fe7b4d7"`);
        await queryRunner.query(`ALTER TABLE "payment_allocations" DROP CONSTRAINT "FK_72095d7b95a6168756ea7d4fbc5"`);
        await queryRunner.query(`ALTER TABLE "payment_allocations" DROP CONSTRAINT "FK_4348f49c6822420b9503ba880b8"`);
        await queryRunner.query(`ALTER TABLE "invoices" DROP CONSTRAINT "FK_65e3145f317bd655481d3f96c74"`);
        await queryRunner.query(`ALTER TABLE "invoice_items" DROP CONSTRAINT "FK_dc991d555664682cfe892eea2c1"`);
        await queryRunner.query(`ALTER TABLE "audit_logs" DROP CONSTRAINT "FK_bd2726fd31b35443f2245b93ba0"`);
        await queryRunner.query(`ALTER TABLE "export_logs" DROP CONSTRAINT "FK_65c069f353e9ea9fe3f6704ca6f"`);
        await queryRunner.query(`ALTER TABLE "login_logs" DROP CONSTRAINT "FK_e2dffa109d0d3dbd94a0a51669c"`);
        await queryRunner.query(`ALTER TABLE "tax_periods" DROP CONSTRAINT "FK_d81a96128c1c18a27887579b9bf"`);
        await queryRunner.query(`ALTER TABLE "tax_periods" DROP CONSTRAINT "FK_78aef69f2e1dfa2a078553bfb67"`);
        await queryRunner.query(`ALTER TABLE "tax_monthly_work_items" DROP CONSTRAINT "FK_eacc9c2849a6d64ab1852a7efd9"`);
        await queryRunner.query(`ALTER TABLE "tax_monthly_work_items" DROP CONSTRAINT "FK_63b37f04b3cf07386071d1dac83"`);
        await queryRunner.query(`ALTER TABLE "tax_monthly_documents" DROP CONSTRAINT "FK_70aec29b537b44c1d25e352821e"`);
        await queryRunner.query(`ALTER TABLE "tax_monthly_documents" DROP CONSTRAINT "FK_a53a90090faa683e0766caeda71"`);
        await queryRunner.query(`ALTER TABLE "files" DROP CONSTRAINT "FK_63c92c51cd7fd95c2d79d709b61"`);
        await queryRunner.query(`ALTER TABLE "tax_contracts" DROP CONSTRAINT "FK_1bf8524bb25eab63d2e91af0d2d"`);
        await queryRunner.query(`ALTER TABLE "tax_contracts" DROP CONSTRAINT "FK_a8432b1e19fcd81c5109c4759e3"`);
        await queryRunner.query(`ALTER TABLE "customers" DROP CONSTRAINT "FK_94c3faf411893c9065d8e3a1ba5"`);
        await queryRunner.query(`ALTER TABLE "customer_staff_relations" DROP CONSTRAINT "FK_98f3bd72761ece595aa544cd8ab"`);
        await queryRunner.query(`ALTER TABLE "customer_staff_relations" DROP CONSTRAINT "FK_c8b5f30220b46fcf4c64b4f6cc0"`);
        await queryRunner.query(`ALTER TABLE "notes" DROP CONSTRAINT "FK_b86c5f2b5de1e7a3d2a428cfb55"`);
        await queryRunner.query(`ALTER TABLE "notes" DROP CONSTRAINT "FK_e04c36c14bc9f01f84cd7655b68"`);
        await queryRunner.query(`ALTER TABLE "person_info" DROP CONSTRAINT "FK_e864b9151380458dd0af28f6e44"`);
        await queryRunner.query(`ALTER TABLE "company_info" DROP CONSTRAINT "FK_6988c6cbd6fb66f2fcbb27f0867"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b23c65e50a758245a33ee35fda"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_87b8888186ca9769c960e92687"`);
        await queryRunner.query(`DROP TABLE "user_roles"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_17022daf3f885f7d35423e9971"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_178199805b901ccd220ab7740e"`);
        await queryRunner.query(`DROP TABLE "role_permissions"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_9d42389a1dd5856406b9a8c728"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_894c17b2b011c55246fe50f078"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_0b8e796a94e331a83318cf41b3"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_515fd84b2a57abbc158687363e"`);
        await queryRunner.query(`DROP TABLE "admin_cases"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a195e34a6d72fc2fc661c2f1ae"`);
        await queryRunner.query(`DROP TABLE "admin_case_tasks"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_1b25bf0cafc578e0324cff5004"`);
        await queryRunner.query(`DROP TABLE "admin_case_documents"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e59cb029ad14d4e405bf18c404"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_60a2d43baaac01885149971b62"`);
        await queryRunner.query(`DROP TABLE "admin_case_interviews"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_fe32f075b4210b25158b5be1e3"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f1101a0737439a005eb075a8f2"`);
        await queryRunner.query(`DROP TABLE "file_access_logs"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_492c9485c10fa86f5021114528"`);
        await queryRunner.query(`DROP TABLE "deposit_transactions"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_433a90689f5b2d8145c5afcb10"`);
        await queryRunner.query(`DROP TABLE "deposit_accounts"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_32b41cdb985a296213e9a928b5"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_8aaa54db3d9827cba0999b7fb2"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d0b02233df1c52323107fe7b4d"`);
        await queryRunner.query(`DROP TABLE "payments"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_72095d7b95a6168756ea7d4fbc"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_4348f49c6822420b9503ba880b"`);
        await queryRunner.query(`DROP TABLE "payment_allocations"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_0457ee681a50419881ea2ee796"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ac0f09364e3701d9ed35435288"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_37669c562a2525929927d9d691"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_65e3145f317bd655481d3f96c7"`);
        await queryRunner.query(`DROP TABLE "invoices"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_dc991d555664682cfe892eea2c"`);
        await queryRunner.query(`DROP TABLE "invoice_items"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_36cd4615fabad14abad075ffc9"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f40ca89b34f101a09acc17c62a"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_0a18c37e4353a67e70f7924e86"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_bd2726fd31b35443f2245b93ba"`);
        await queryRunner.query(`DROP TABLE "audit_logs"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_7a21cf8208b231827f76a53f6b"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_65c069f353e9ea9fe3f6704ca6"`);
        await queryRunner.query(`DROP TABLE "export_logs"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_2b01a6f73584d7fde0ed64435c"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e2dffa109d0d3dbd94a0a51669"`);
        await queryRunner.query(`DROP TABLE "login_logs"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_8d48b76ad9c949f2da6bd72369"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d81a96128c1c18a27887579b9b"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_78aef69f2e1dfa2a078553bfb6"`);
        await queryRunner.query(`DROP TABLE "tax_periods"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_63b37f04b3cf07386071d1dac8"`);
        await queryRunner.query(`DROP TABLE "tax_monthly_work_items"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a53a90090faa683e0766caeda7"`);
        await queryRunner.query(`DROP TABLE "tax_monthly_documents"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d2eddbeffbb889f6dbc4000259"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e9f32fe4b7bcf2dfb8751d0a87"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_56c45a88d18bd08a3abaa532a2"`);
        await queryRunner.query(`DROP TABLE "files"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_1bf8524bb25eab63d2e91af0d2"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_3d138da760f80cf89b6a1bbeaf"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a8432b1e19fcd81c5109c4759e"`);
        await queryRunner.query(`DROP TABLE "tax_contracts"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_94c3faf411893c9065d8e3a1ba"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_724f8799ff8921a88eb5253d2f"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a1dded0c9e77a3e62a09d20ed8"`);
        await queryRunner.query(`DROP TABLE "customers"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_29f12cee9b015a4fb82fd016d0"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_98f3bd72761ece595aa544cd8a"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c8b5f30220b46fcf4c64b4f6cc"`);
        await queryRunner.query(`DROP TABLE "customer_staff_relations"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e04c36c14bc9f01f84cd7655b6"`);
        await queryRunner.query(`DROP TABLE "notes"`);
        await queryRunner.query(`DROP TABLE "person_info"`);
        await queryRunner.query(`DROP TABLE "company_info"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_3676155292d72c67cd4e090514"`);
        await queryRunner.query(`DROP TABLE "users"`);
        await queryRunner.query(`DROP TABLE "roles"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_8b634526cdd01f2adba6c7ac07"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c87bc220c276c0281bc0610885"`);
        await queryRunner.query(`DROP TABLE "permissions"`);
    }

}
